package com.ecas.domain;

import com.ecas.base.BaseDomain;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SaasService generated by hbm2java
 */
@Entity
@Table(name = "ecas_api_key")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "ecas_api_key")
public class APIKey extends BaseDomain implements java.io.Serializable {
    private static final long serialVersionUID = 8248943666497556860L;
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    private Integer id;

    @Column(name = "NAME", length = 255, nullable = false)
    private String name;

    @Column(name = "ACTIVE")
    private boolean active;

    @Lob
    @Column(name = "DESCRIPTION")
    private String description;

    @Column(name = "CODE")
    private String code;

    @Column(name = "WHITE_LIST_IP")
    private String whiteListIP;

    @Column(name = "API_ID")
    private String API;

    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getWhiteListIP() {
        return whiteListIP;
    }

    public void setWhiteListIP(String whiteListIP) {
        this.whiteListIP = whiteListIP;
    }

    public String getAPI() {
        return API;
    }

    public void setAPI(String API) {
        this.API = API;
    }
}
