package com.ecas.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.ecas.base.BaseDomain;

/**
 * SystemMessage generated by hbm2java
 */
@Entity
@Table(name = "ecas_system_message")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE, region = "system_message")
public class SystemMessage extends BaseDomain implements java.io.Serializable {
    private static final long serialVersionUID = -3407812439563831240L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ID", unique = true, nullable = false)
    private int id;
    @Column(name = "CODE", length = 255, nullable = false)
    private String code;
    @Column(name = "VALUE", length = 1000)
    private String value;

    public SystemMessage() {
    }

    public SystemMessage(int id) {
        this.id = id;
    }

    public SystemMessage(int id, String code, String value) {
        this.id = id;
        this.code = code;
        this.value = value;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
